### ISSUE TITLE
Error on connect

### ISSUE THREAD

**Issue by Mitchell-Hampton** [gerritv/Grbl-Panel#78] opened 2016-12-12 10:56 UTC
I am getting a unhanded exception every time i connect to my grbl. 
![image](https://cloud.githubusercontent.com/assets/20833493/21096727/f2971ba0-c0c5-11e6-9f43-f061c73218b0.png) i can continue but it is pointless as all data seems to be garbage. I tried debugging it and it seems to point to GrblPosition.vb line 97 as workPos is only 2 long and it is trying to access the third member. I tried fixing quickly with no understanding of the system by adding some checks which got rid of the error popup but my data was meaningless. 
![image](https://cloud.githubusercontent.com/assets/20833493/21096875/98ace556-c0c6-11e6-9c05-dbbcf452cb1f.png)

**Comment by Mitchell-Hampton** [comment] 2016-12-12 10:58
I will try this on my other computer tomorrow to test if its something weird on my PC as I assume its not common at all since it completely inhibits functionality

**Comment by BernardG** [comment] 2016-12-12 11:11
Thanks for reporting this, Mitchell. What is the exact version of Grbl-Panel you are using? This ring a bell, I saw this while localizing, and believe to have fixed it! If you are using release V1.0.9.8, then I'll look at this, as I may have created a bug! (Or you may have to use Windows in French, as it works for me here! LOL)

**Comment by gerritv** [comment] 2016-12-12 12:23
The cause seems to be that GrblPanel is not recognizing your Grbl as being 1.x version so it is executing the Grbl 0.9 protocol code. E.g. you should see the Override section of display on RH bottom of GrblPanel as well as the pin status'
What version of Grbl are you running? Is it a custom version?

**Comment by Mitchell-Hampton** [comment] 2016-12-12 20:01
I have tried both V1.0.9.8 and V1.0.9.7. I am running Grbl1.1e.

**Comment by gerritv** [comment] 2016-12-12 21:28
Very puzzling then. 
Can you show what is in Status panel around the time that Grbl ID string appears?
If you click Details on the Exception popup, what line does it indicate the error is detected on?

**Comment by Mitchell-Hampton** [comment] 2016-12-12 21:29
I have just run V1.0.9.7 on my other computer and a new Arduino and it works fine. Is it possible that it its caused by my USB-Serial adapter that I use on the other system?

**Comment by gerritv** [comment] 2016-12-12 21:38
There are some that cause problems, CH340 is known to have issues at 115200 bd. 
Are you ok with closing this issue then?

**Comment by Mitchell-Hampton** [comment] 2016-12-12 21:43
Yea it is OK with me, Thank you this whole Grbl thing is amazing :).

**Closed** 2016-12-12 22:03 UTC
